// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-5UkIjWlKISSEOUNRXMNNapWUs2tgPBM',
    appId: '1:582527568797:web:4b21e2ca305bb75bcdbd74',
    messagingSenderId: '582527568797',
    projectId: 'noteappuasmade',
    authDomain: 'noteappuasmade.firebaseapp.com',
    storageBucket: 'noteappuasmade.firebasestorage.app',
    measurementId: 'G-NZ1SF9MWBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAclbXLa97aoG5BTdZFy_RE44WtdaNglk',
    appId: '1:582527568797:android:985929f800f541facdbd74',
    messagingSenderId: '582527568797',
    projectId: 'noteappuasmade',
    storageBucket: 'noteappuasmade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClOgqgT9iO41DyLH8g2S8VMKvSVQkI1cE',
    appId: '1:582527568797:ios:0a037e5d93c0983dcdbd74',
    messagingSenderId: '582527568797',
    projectId: 'noteappuasmade',
    storageBucket: 'noteappuasmade.firebasestorage.app',
    iosBundleId: 'com.example.noteTakingApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClOgqgT9iO41DyLH8g2S8VMKvSVQkI1cE',
    appId: '1:582527568797:ios:0a037e5d93c0983dcdbd74',
    messagingSenderId: '582527568797',
    projectId: 'noteappuasmade',
    storageBucket: 'noteappuasmade.firebasestorage.app',
    iosBundleId: 'com.example.noteTakingApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-5UkIjWlKISSEOUNRXMNNapWUs2tgPBM',
    appId: '1:582527568797:web:b1d543aadb160cadcdbd74',
    messagingSenderId: '582527568797',
    projectId: 'noteappuasmade',
    authDomain: 'noteappuasmade.firebaseapp.com',
    storageBucket: 'noteappuasmade.firebasestorage.app',
    measurementId: 'G-NRX1B9R5H9',
  );
}
